# Generated by Django 2.0.5 on 2018-08-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='image_path',
            field=models.CharField(default='images/notfound.jpg', max_length=256),
        ),
    ]
