# Generated by Django 2.0.5 on 2018-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_socialmedia_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
