# Generated by Django 2.0.5 on 2018-08-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_socialmedia_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='greetings',
            field=models.CharField(default='Greetings', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='intro_text',
            field=models.TextField(default='Intro Text'),
        ),
    ]
