# Generated by Django 2.0.5 on 2018-08-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_auto_20180806_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldescription',
            name='active',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='personaldescription',
            name='checked',
            field=models.CharField(default='checked', max_length=10),
        ),
        migrations.AddField(
            model_name='personaldescription',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
