# Generated by Django 2.0.5 on 2018-08-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_auto_20180807_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldescription',
            name='active',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personaldescription',
            name='checked',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
