# Generated by Django 2.0.5 on 2018-08-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_auto_20180807_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldescription',
            name='hide',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
