# Generated by Django 2.0.5 on 2018-08-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_personaldescription_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='location',
            field=models.TextField(default='Toronto, ON'),
        ),
    ]
