# Generated by Django 2.0.5 on 2018-08-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_personaldata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='loc_icon',
            field=models.TextField(default='images/location-icon'),
        ),
    ]
