# Generated by Django 2.0.5 on 2018-08-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_personaldata_loc_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='loc_icon',
            field=models.CharField(default='images/location-icon', max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='location',
            field=models.CharField(default='Toronto, ON', max_length=30),
        ),
    ]
